const NOTION_URL = 'https://www.notion.so';

const TAKE_CANVAS_SHOT = 'TAKE_CANVAS_SHOT';
const TAKE_SCREEN_SHOT = 'TAKE_SCREEN_SHOT';
const GET_CURRENT_TAB_ID = 'GET_CURRENT_TAB_ID';
// Get video's position in the screen
const GET_VIDEO_POSITION_DATA = 'GET_VIDEO_POSITION_DATA';
const SHOW_ACTIVE_VIDEO = 'SHOW_ACTIVE_VIDEO';
